In [38]:
# The following notebook uses Support Vector Machines on the famous Iris dataset.
# This dataset was introduced by the British statistician and biologist Sir Ronald Fisher 
# in his 1936 paper The use of multiple measurements in taxonomic problems

# This dataset is openly available at UCI Machine Learning Repository

In [39]:
#The iris dataset contains measurements for 150 iris flowers from three different species.

#The three classes in the Iris dataset:

#    Iris-setosa (n=50)
#    Iris-versicolor (n=50)
#    Iris-virginica (n=50)

# The four features of the Iris dataset:

#    sepal length in cm
#    sepal width in cm
#    petal length in cm
#    petal width in cm

## Get the data

#**Use seaborn to get the iris data by using: iris = sns.load_dataset('iris') **

In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline



In [41]:
# Import the dataset using Seaborn library
iris=pd.read_csv('C:/Users/admin/Desktop/IRIS.csv')

In [42]:
# Checking the dataset
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
# Separating the independent variables from dependent variables
x=iris.iloc[:,:-1]
y=iris.iloc[:,5]
from sklearn import preprocessing
from sklearn import utils
lab_enc = preprocessing.LabelEncoder()
training_scores_encoded = lab_enc.fit_transform(y)
print(training_scores_encoded)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [45]:
x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.30)

In [46]:
from sklearn.svm import SVC
model=SVC(kernel= 'linear')
#iris

In [47]:
model.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [48]:
pred=model.predict(x_test)

In [49]:
# Importing the classification report and confusion matrix
from sklearn.metrics import classification_report, confusion_matrix

In [50]:
print(confusion_matrix(y_test,pred))

[[15  0  0]
 [ 0 16  0]
 [ 0  0 14]]


In [51]:
print(classification_report(y_test, pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       1.00      1.00      1.00        16
 Iris-virginica       1.00      1.00      1.00        14

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45

